name: Build
on:
  pull_request:
  push:
    branches: [main]
    tags: [v*]
jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022, macos-12, ubuntu-22.04]
        addrsize: ["64"]
    continue-on-error: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Homebrew Packages
        if: ${{ runner.os == 'macOS' }}
        shell: bash
        run: brew install autoconf automake gettext libtool
      - name: Setup Apt Packages
        if: ${{ runner.os == 'Linux' }}
        shell: bash
        run: | 
          sudo apt-get update
          sudo apt-get -y install autoconf automake autopoint gettext
      - uses: secondlife/action-autobuild@v5
        with:
          addrsize: ${{ matrix.addrsize }}
  release:
    needs: build
    runs-on: [ubuntu-latest]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: secondlife/action-autobuild-release@v3
        with:
          public: true
